Pretty-fy the vm-script

diff --git a/util/clean b/util/clean
--- a/util/clean
+++ b/util/clean
@@ -5,80 +5,69 @@
 # DELETES ALL CONTENT ON ALL VMS!
 #  - Kristian
 
-
-set -e
-set -x
-
+AMOUNT=9
+echo "Destroying any running virtual machines. Ignore any error messages about them not running."
+sleep 1
+# Always stop all of them.
 for a in `seq 1 12`; do
 	virsh destroy training$a;
 	sleep 0.1;
 done
 
+echo "Stopping libvirt-bin:"
 service libvirt-bin stop || echo "already stopped?"
+echo "Pids for kvm: (should be blank)"
 pidof kvm
+echo "Hit any key to continue. Or write a poem, that's ok too."
 read tmp
-lvremove -f /dev/training-laptop/training-snap1
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap2
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap3
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap4
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap5
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap6
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap7
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap8
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap9
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap10
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap11
-sleep 0.5
-lvremove -f /dev/training-laptop/training-snap12
-sleep 0.5
 
+set -e
+echo "Removing old snapshots."
+for a in `seq 1 $AMOUNT`; do
+	lvremove -f /dev/training-laptop/training-snap$a
+	sleep 0.5
+done
 sleep 2
-lvcreate --size 4G  --snapshot --name training-snap1 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap2 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap3 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap4 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap5 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap6 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap7 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap8 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap9 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap10 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap11 /dev/training-laptop/training1 
-sleep 0.5
-lvcreate --size 4G  --snapshot --name training-snap12 /dev/training-laptop/training1 
-sleep 0.5
 
+echo "Creating new snapshots."
+for a in `seq 1 $AMOUNT`; do
+	lvcreate --size 4G  --snapshot --name training-snap$a /dev/training-laptop/training1
+	sleep 0.5
+done
+
+echo "Starting libvirt"
 service libvirt-bin start
-
 sleep 5
 
-for a in `seq 2 12`; do
+pw=squiddo
+rootpw="VHBUhvFHwlkgx5KTj8gPW/"
+echo "Passwordbase: ${pw}"
+echo "Root: ${rootpw}"
+echo "Logging in to machine 2 through $AMOUNT to reset hostnames."
+echo "This will take some time."
+for a in `seq 2 $AMOUNT`; do
 	sleep 5
 	virsh start training$a
 	sleep 25
-	ssh root@training1.local sed -i "s/training1/training$a/g" /etc/hosts /etc/motd  /etc/hostname 
+	( echo ${pw}$a; sleep 2; echo ${pw}$a; sleep 2; ) | ssh root@training1.local passwd training
+	( echo ${rootpw}; sleep 2; echo ${rootpw}; sleep 2; ) | ssh root@training1.local passwd
+	ssh root@training1.local sed -i "s/training1/training$a/g" /etc/hosts /etc/motd  /etc/hostname
+	echo "Rebooting training$a"
 	ssh root@training1.local reboot
 done
-#virsh start training1
-#pw=squiddo
-#( echo ${pw}1; sleep 2; echo ${pw}1; sleep 2; ) | passwd training
+
+echo "Specialcasing the _real_ training1. Starting it."
+sleep 5
+virsh start training1
+sleep 25
+echo "Trying to set the password for training1."
+( echo ${pw}1; sleep 2; echo ${pw}1; sleep 2; ) | ssh root@training1.local passwd training
+( echo ${rootpw}; sleep 2; echo ${rootpw}; sleep 2; ) | ssh root@training1.local passwd
+
+echo "Summary:"
+for a in `seq 1 $AMOUNT`; do
+	sleep 2
+	echo "training$a.local is:"
+	ssh root@training$a.local ip addr | grep inet | egrep -v '(127.0.0.1|6 ::1|fe80::)'
+	echo
+done
