Improve building and testing
Implements make check for PHP-material too, which simply does a syntax
check on the PHP (better than nothing). It also changes how make check
works so it's possible to do in parallel.

Also fixes make dist, so we get three different tar balls, and they work.

diff --git a/vcl/Makefile b/vcl/Makefile
--- a/vcl/Makefile
+++ b/vcl/Makefile
@@ -2,32 +2,35 @@
 SHELL = /bin/sh 
 vcls = *.vcl
 
-check: $(vcls)
-	@for a in $(vcls); do \
-		echo -n Testing $$a... ;\
-		if egrep -q '^(backend|director)' $$a; then \
-			foo=`varnishd -n $$PWD/../build/ -C -f $$a 2>&1 > /dev/null` ;\
-			if [ -z "$$foo" ]; then \
-				echo "OK"; \
-			 else \
-				echo "failed"; \
-				echo "$$foo"; \
-				exit 1; \
-			 fi;\
-		else \
-			test -e $$a.tmp && exit 2;\
-			cat backend.vcl $$a > $$a.tmp; \
-			foo=`varnishd -C -n $$PWD/../build/ -f $$a.tmp 2>&1 > /dev/null` ;\
-			rm $$a.tmp ; \
-			if [ -z "$$foo" ]; then \
-				echo "OK"; \
-			 else \
-				echo "failed"; \
-				echo "$$foo"; \
-				exit 1;\
-			 fi; \
-		fi;\
-	done
+objs = $(addsuffix .done,$(basename $(notdir $(wildcard *vcl))))
+
+%.done: %.vcl
+	@if egrep -q '^(backend|director)' $<; then \
+		foo=`varnishd -n $$PWD/../build/ -C -f $< 2>&1 > /dev/null` ;\
+		if [ -z "$$foo" ]; then \
+			echo "VCL OK: $<"; \
+		 else \
+			echo "VCL FAILED: $<"; \
+			echo "$$foo"; \
+			exit 1; \
+		 fi;\
+	else \
+		test -e $<.tmp && exit 2;\
+		cat backend.vcl $< > $<.tmp; \
+		foo=`varnishd -C -n $$PWD/../build/ -f $<.tmp 2>&1 > /dev/null` ;\
+		rm $<.tmp ; \
+		if [ -z "$$foo" ]; then \
+			echo "VCL OK: $<"; \
+		 else \
+			echo "VCL FAILED: $<"; \
+			echo "$$foo"; \
+			exit 1;\
+		 fi; \
+	fi;\
+	
+
+check: $(objs)
+	
 
 .PHONY: check
 
